Init:
  unstash: []
  stashes:
  - name: "source"
    includes: "**/*"
    excludes: ".pipeline/**"

'Pull-Request Voting':
  unstash: ['source','git']
  stashes: []

'Build':
  unstash: ['source','git']
  stashes: []

'Acceptance':
  unstash: ['buildResult']
  stashes: []
